config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "posts#index" # トップページを設定
  get '/post_form', to: 'posts#new'
  resources :posts
  get 'categories/reduce_salt', to: 'posts#reduce_salt'
  get 'categories/reduce_sugar', to: 'posts#reduce_sugar'
  get 'categories/high_protein', to: 'posts#high_protein'
  get 'categories/obesity_prevention', to: 'posts#obesity_prevention'
  get 'categories/cold_prevention', to: 'posts#cold_prevention'
  get 'categories/others', to: 'posts#others'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ActiveHash::Base
  self.data = [
    { id: 1, name: '減塩' },
    { id: 2, name: '減糖' },
    { id: 3, name: '高タンパク質' },
    { id: 4, name: '肥満対策' },
    { id: 5, name: '風邪対策' },
    { id: 6, name: 'その他' }
  ]

end

app/models/post.rb
class Post < ApplicationRecord
  has_one_attached :image
  belongs_to_active_hash :category
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true

  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth, unless: :devise_controller? || :skip_basic_auth?

  private

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV['BASIC_AUTH_USER'] && password == ENV['BASIC_AUTH_PASSWORD']
    end
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up,
                                      keys: [:name])
  end

  def skip_basic_auth?
    controller_name == 'sessions' && action_name == 'destroy'
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def create
    @post = current_user.posts.build(post_params)

    if @post.save
      redirect_to @post, notice: 'Post was successfully created.'
    else
      render :new
    end
  end

  def new
    @post = Post.new
  end

  def index
    @latest_posts = Post.order(created_at: :desc).limit(3)
  end

  def show
    @post = Post.find(params[:id])
  end

  def reduce_salt
    @posts = Post.where(category_id: 1)
  end

  def reduce_sugar
    @posts = Post.where(category_id: 2)
  end

  def high_protein
    @posts = Post.where(category_id: 3)
  end

  def obesity_prevention
    @posts = Post.where(category_id: 4)
  end

  def cold_prevention
    @posts = Post.where(category_id: 5)
  end

  def others
    @posts = Post.where(category_id: 6)
  end

  private

  def post_params
    params.require(:post).permit(:title, :content, :category_id, :image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/categories/cold_prevention.html.erb
<div class="container">
  <h1 class="text-center mt-4">風邪予防カテゴリーの投稿</h1>
  <div class="row justify-content-center">
    <!-- 投稿の表示 -->
    <% @posts.each do |post| %>
      <div class="col-md-4 mb-4">
        <%= image_tag post.image.variant(resize: "300x200") if post.image.attached? %>
        <h3 class="mt-2"><%= post.title %></h3>
        <!-- その他の投稿情報 -->
      </div>
    <% end %>
  </div>
</div>

app/views/categories/high_protein.html.erb
<div class="container">
  <h1 class="text-center mt-4">高タンパク質カテゴリーの投稿</h1>
  <div class="row justify-content-center">
    <!-- 投稿の表示 -->
    <% @posts.each do |post| %>
      <div class="col-md-4 mb-4">
        <%= image_tag post.image.variant(resize: "300x200") if post.image.attached? %>
        <h3 class="mt-2"><%= post.title %></h3>
        <!-- その他の投稿情報 -->
      </div>
    <% end %>
  </div>
</div>

app/views/categories/obesity_prevention.html.erb
<div class="container">
  <h1 class="text-center mt-4">肥満対策カテゴリーの投稿</h1>
  <div class="row justify-content-center">
    <!-- 投稿の表示 -->
    <% @posts.each do |post| %>
      <div class="col-md-4 mb-4">
        <%= image_tag post.image.variant(resize: "300x200") if post.image.attached? %>
        <h3 class="mt-2"><%= post.title %></h3>
        <!-- その他の投稿情報 -->
      </div>
    <% end %>
  </div>
</div>

app/views/categories/others.html.erb
<div class="container">
  <h1 class="text-center mt-4">その他カテゴリーの投稿</h1>
  <div class="row justify-content-center">
    <!-- 投稿の表示 -->
    <% @posts.each do |post| %>
      <div class="col-md-4 mb-4">
        <%= image_tag post.image.variant(resize: "300x200") if post.image.attached? %>
        <h3 class="mt-2"><%= post.title %></h3>
        <!-- その他の投稿情報 -->
      </div>
    <% end %>
  </div>
</div>

app/views/categories/reduce_salt.html.erb
<!-- app/views/categories/reduce_salt.html.erb -->
<div class="container">
  <h1 class="text-center mt-4">減塩カテゴリーの投稿</h1>
  <div class="row justify-content-center">
    <!-- 投稿の表示 -->
    <% @posts.each do |post| %>
      <div class="col-md-4 mb-4">
        <%= image_tag post.image.variant(resize: "300x200") if post.image.attached? %>
        <h3 class="mt-2"><%= post.title %></h3>
        <!-- その他の投稿情報 -->
      </div>
    <% end %>
  </div>
</div>

app/views/categories/reduce_sugar.html.erb
<div class="container">
  <h1 class="text-center mt-4">減糖カテゴリーの投稿</h1>
  <div class="row justify-content-center">
    <!-- 投稿の表示 -->
    <% @posts.each do |post| %>
      <div class="col-md-4 mb-4">
        <%= image_tag post.image.variant(resize: "300x200") if post.image.attached? %>
        <h3 class="mt-2"><%= post.title %></h3>
        <!-- その他の投稿情報 -->
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SyokukatuApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <%= stylesheet_link_tag "bootstrap.min.css", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "shared/header" %>
    <%= yield %>
    <%= render "shared/footer" %>
  </body>
</html>

app/views/posts/_form.html.erb
<div class="container">
  <div class="row justify-content-center mt-5">
    <div class="col-lg-8">
      <h1 class="text-center mb-4">新しい投稿</h1>

      <%= form_with(model: post, local: true) do |form| %>
        <% if post.errors.any? %>
          <div class="alert alert-danger">
            <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>
            <ul>
              <% post.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

        <div class="mb-6 mt-5">
          <%= form.label :title, class: "form-label" %>
          <%= form.text_field :title, class: "form-control", placeholder: "タイトルを入力してください" %>
        </div>

        <div class="mb-6 mt-5">
          <%= form.label :content, class: "form-label" %>
          <%= form.text_area :content, class: "form-control", placeholder: "内容を入力してください", rows: 5 %>
        </div>

        <div class="mb-6 mt-5">
          <%= form.label :image, class: "form-label" %>
          <%= form.file_field :image, class: "form-control" %>
        </div>

        <div class="mb-6 mt-5">
          <%= form.label :category_id, class: "form-label" %>
          <% Category.all.each do |category| %>
          <div class="form-check">
            <%= form.radio_button :category_id, category.id, id: "category_#{category.id}", class: "form-check-input" %>
            <%= form.label "category_#{category.id}", category.name, class: "form-check-label" %>
          </div>
          <% end %>
        </div>


        <% if user_signed_in? %>
          <div class="text-center mt-5">
            <%= form.submit "投稿する", class: "btn btn-primary" %>
          </div>
        <% else %>
          <p class="text-center mt-5">投稿するにはログインしてください。</p>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/index.html.erb
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
        .background-container {
            background-image: url('<%= asset_path('syokukatu.png') %>');
            min-height: 100vh;
            background-size: cover;
            background-position: center;
        }

        .content-container {
            padding: 20px;
        }
    </style>
</head>

<body>
    <div class="background-container">
        <div class="container content-container">
            <div class="row justify-content-center">
                <div class="col-lg-6 d-flex flex-column justify-content-center align-items-center">
                    <h1 class="text-center mb-4 fw-bold">食活しよう！！</h1>
                    <p class="text-center fw-bold fs-5">当アプリは食事で生活習慣病などの身近な病気を</p>
                    <p class="text-center fw-bold fs-5">予防できるようにしたいと思い作られたものです。</p>
                    <p class="text-center fw-bold fs-5">予防につながる食材や料理を写真付きで</p>
                    <p class="text-center fw-bold fs-5">カテゴリー別で投稿して下さい。</p>
                </div>
                <div class="col-lg-6">
                    <div class="btn-group">
                        <button type="button" class="btn btn-danger dropdown-toggle" data-bs-toggle="dropdown"
                            aria-expanded="false" style="width: 200px; height: 80px; font-size: 30px;">
                            カテゴリー
                        </button>
                        <ul class="dropdown-menu">
                            <% Category.all.each do |category| %>
                            <li><a class="dropdown-item" href="#"><%= category.name %></a></li>
                            <% end %>
                            <li><hr class="dropdown-divider"></li>
                            <li><a class="dropdown-item" href="#">Separated link</a></li>
                        </ul>
                    </div>
                    <div class="col-lg-6 mt-3">
                        <a href="<%= new_post_path %>" class="btn btn-danger"
                            style="width: 200px; height: 80px; font-size: 30px;">投稿する</a>
                    </div>
                </div>
            </div>
            <!-- 最新の投稿を表示する部分 -->
            <div class="row">
                <% @latest_posts.each do |post| %>
                <div class="col-lg-4 mb-4">
                    <%= link_to post_path(post) do %>
                    <%= image_tag post.image.variant(resize_to_fill: [300, 200]) if post.image.attached? %>
                    <h3><%= post.title %></h3>
                    <p><%= post.content.truncate(50) %></p>
                    <% end %>
                </div>
                <% end %>
            </div>
            <!-- /最新の投稿を表示する部分 -->
        </div>
    </div>
</body>

</html>

app/views/posts/new.html.erb
<div class="container">
  <div class="row justify-content-center mt-5">
    <div class="col-lg-8">
      <h1 class="text-center mb-4">新しい投稿</h1>

      <%= render 'form', post: @post %>
      
    </div>
  </div>
</div>

app/views/posts/post_form.html.erb
%= form_with(model: post, local: true) do |form| %>
  <div class="mb-3">
    <%= form.label :title, class: "form-label" %>
    <%= form.text_field :title, class: "form-control", placeholder: "タイトルを入力してください" %>
  </div>
  <div class="mb-3">
    <%= form.label :content, class: "form-label" %>
    <%= form.text_area :content, class: "form-control", placeholder: "内容を入力してください" %>
  </div>
  <div class="mb-3">
    <%= form.label :image, class: "form-label" %>
    <%= form.file_field :image, class: "form-control" %>
  </div>
  <%= form.submit "投稿する", class: "btn btn-primary" %>
<% end %>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>

<%= image_tag @post.image %>

<p><%= @post.content %></p>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="error-alert">
    <ul>
      <% model.errors.full_messages.each do |message| %>
      <li class='error-message'><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer fixed-bottom">
  <div class="container">
    <div class="row">
      <div class="col-md-4">
        <div class="footer-details">
          <h2 class="footer-content-head">食活とは？</h2>
          <ul class="list-unstyled">
            <li><%= link_to '会社概要（運営会社)', "#", class: "footer-link" %></li>
          </ul>
        </div>
      </div>
      <div class="col-md-4">
        <div class="footer-details">
          <h2 class="footer-content-head">食活を見る</h2>
          <ul class="list-unstyled">
            <li><%= link_to 'カテゴリー一覧', "#", class: "footer-link" %></li>
          </ul>
        </div>
      </div>
      <div class="col-md-4">
        <div class="footer-details">
          <h2 class="footer-content-head">最新情報</h2>
          <ul class="list-unstyled">
            <li><%= link_to 'お知らせ', "#", class: "footer-link" %></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</footer>

app/views/shared/_header.html.erb
<header class='top-page-header bg-secondary' style="height: 120px;">
  <div class='container'>
    <div class='row justify-content-center'>
      <div class='col-lg-6'>
        <div class='nav'>
          <ul class='lists-right' style="list-style-type: none; display: flex; justify-content: center;">
            <% if user_signed_in? %>
            <li class="nav-item" style="margin-right: 30px;">
                <%= link_to(root_path, class: "navbar-brand text-light me-2") do %>
                  <svg xmlns="http://www.w3.org/2000/svg" width="64" height="64" fill="currentColor" class="bi bi-house" viewBox="0 0 16 16">
                    <path d="M0 5l8-5 8 5v9.75a.25.25 0 0 1-.25.25h-3.5a.75.75 0 0 0-.75.75v-3h-5v3a.75.75 0 0 0-.75-.75h-3.5a.25.25 0 0 1-.25-.25V5z"/>
                    <path d="M13 3.268V1h-2v2.268L8 2l-3 2V1H3v2.268L1 3.268V5l7 4.667L15 5v-.732L13 5z"/>
                  </svg>
                <% end %>
              </li>
              <li class="list-inline-item me-2">
                <%= button_to 'ログアウト', destroy_user_session_path, method: :delete, class: "btn btn-success btn-lg", style: "width: 200px; height: 80px; font-size: 30px;", data: { confirm: '本当にログアウトしますか？' } %>
              </li>
            <% else %>
              <li class="nav-item" style="margin-right: 30px;">
                <%= link_to(root_path, class: "navbar-brand text-light me-2") do %>
                  <svg xmlns="http://www.w3.org/2000/svg" width="64" height="64" fill="currentColor" class="bi bi-house" viewBox="0 0 16 16">
                    <path d="M0 5l8-5 8 5v9.75a.25.25 0 0 1-.25.25h-3.5a.75.75 0 0 0-.75.75v-3h-5v3a.75.75 0 0 0-.75-.75h-3.5a.25.25 0 0 1-.25-.25V5z"/>
                    <path d="M13 3.268V1h-2v2.268L8 2l-3 2V1H3v2.268L1 3.268V5l7 4.667L15 5v-.732L13 5z"/>
                  </svg>
                <% end %>
              </li>
              <li class="list-inline-item me-2">
                <%= link_to '新規登録', new_user_registration_path, class: "btn btn-primary", role: "button", style: "width: 200px; height: 80px; font-size: 30px;" %>
              </li>
              <li class="list-inline-item me-2">
                <%= link_to 'ログイン', new_user_session_path, class: "btn btn-success", role: "button", style: "width: 200px; height: 80px; font-size: 30px;" %>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </div>
</header>